export const COUNTRIES = [
  { code: 'US', flag: '🇺🇸', name: '美国' },
  { code: 'CN', flag: '🇨🇳', name: '中国' },
  { code: 'JP', flag: '🇯🇵', name: '日本' },
  { code: 'GB', flag: '🇬🇧', name: '英国' },
  { code: 'DE', flag: '🇩🇪', name: '德国' },
  { code: 'FR', flag: '🇫🇷', name: '法国' },
  { code: 'IT', flag: '🇮🇹', name: '意大利' },
  { code: 'CA', flag: '🇨🇦', name: '加拿大' },
  { code: 'AU', flag: '🇦🇺', name: '澳大利亚' },
  { code: 'BR', flag: '🇧🇷', name: '巴西' },
  { code: 'IN', flag: '🇮🇳', name: '印度' },
  { code: 'RU', flag: '🇷🇺', name: '俄罗斯' },
  { code: 'KR', flag: '🇰🇷', name: '韩国' },
  { code: 'SG', flag: '🇸🇬', name: '新加坡' },
  { code: 'ES', flag: '🇪🇸', name: '西班牙' },
  { code: 'NL', flag: '🇳🇱', name: '荷兰' },
  { code: 'SE', flag: '🇸🇪', name: '瑞典' },
  { code: 'CH', flag: '🇨🇭', name: '瑞士' },
  { code: 'MX', flag: '🇲🇽', name: '墨西哥' },
  { code: 'ID', flag: '🇮🇩', name: '印度尼西亚' },
  { code: 'TR', flag: '🇹🇷', name: '土耳其' },
  { code: 'SA', flag: '🇸🇦', name: '沙特阿拉伯' },
  { code: 'PL', flag: '🇵🇱', name: '波兰' },
  { code: 'TH', flag: '🇹🇭', name: '泰国' },
  { code: 'BE', flag: '🇧🇪', name: '比利时' },
  { code: 'IL', flag: '🇮🇱', name: '以色列' },
  { code: 'AE', flag: '🇦🇪', name: '阿联酋' },
  { code: 'AT', flag: '🇦🇹', name: '奥地利' },
  { code: 'NO', flag: '🇳🇴', name: '挪威' },
  { code: 'DK', flag: '🇩🇰', name: '丹麦' },
  { code: 'IE', flag: '🇮🇪', name: '爱尔兰' },
  { code: 'NZ', flag: '🇳🇿', name: '新西兰' },
  { code: 'ZA', flag: '🇿🇦', name: '南非' },
  { code: 'FI', flag: '🇫🇮', name: '芬兰' },
  { code: 'PT', flag: '🇵🇹', name: '葡萄牙' },
  { code: 'GR', flag: '🇬🇷', name: '希腊' },
  { code: 'CZ', flag: '🇨🇿', name: '捷克' },
  { code: 'HU', flag: '🇭🇺', name: '匈牙利' },
  { code: 'RO', flag: '🇷🇴', name: '罗马尼亚' },
  { code: 'CL', flag: '🇨🇱', name: '智利' },
  { code: 'PH', flag: '🇵🇭', name: '菲律宾' },
  { code: 'VN', flag: '🇻🇳', name: '越南' },
  { code: 'MY', flag: '🇲🇾', name: '马来西亚' },
  { code: 'CO', flag: '🇨🇴', name: '哥伦比亚' },
  { code: 'BD', flag: '🇧🇩', name: '孟加拉国' },
  { code: 'EG', flag: '🇪🇬', name: '埃及' },
  { code: 'AR', flag: '🇦🇷', name: '阿根廷' },
  { code: 'UA', flag: '🇺🇦', name: '乌克兰' },
  { code: 'PE', flag: '🇵🇪', name: '秘鲁' },
  { code: 'KE', flag: '🇰🇪', name: '肯尼亚' }
] as const;